export const CDbNameLabel = {
    mysql: "MySQL",
    mongodb: "Mongo DB",
    postgresql: "Postgres",
    oracle: "Oracle",
    otherDb: "Other database",
    createDbCredentials: "Create database credentials",
    noDbCredentials: "No database credentials",
    messageDBUser: "Enter your user database :",
    messageDBPwd: "Enter the password of database :",
    messageDBName: "Enter the name of database :",
    placeholderDBUser: "user",
    placeholderDBHost: "localhost",
    placeholderDBName: "db_toto",
    pwdMask: "*",
    dbUserInvalidValue: "Please user database can't be empty.",
    dbPwdInvalidValue: "Please a database password can't be empty.",
    dbHostInvalidValue: "Please a database host can't be empty.",
    dbNameInvalidValue: "Please database name can't be empty.",
    dbUserBadPattern: "Please enter a valide user database.",
    dbHostBadPattern: "Please enter a valide database host.",
    dbPwdBadPattern: "Please enter a valide database password.",
    dbNameBadPattern: "Please enter a valide database name.",
    messageDBHost: "Enter the host of database :",
    messageDBPort: "Enter the port of database :",
    placeholderDBPort: "mysql: 3306",
    dbPortInvalidValue: "Please a database port can't be empty.",
    dbPortBadPattern: "Please enter a valide database port.",
};